CREATE VIEW REL_WINE_VINEYARD_EXTENDED
(
    WINE_ID,
    WINE_NAME,
    WINE_YEAR,
    WINE_PRODUCER,
    WINE_TECHNOTES,
    VINEYARD_ID,
    VINEYARD_NAME
)
AS
SELECT 
	W.ID,
    W.NAME,
    W.YEAR,
    W.PRODUCER,
    W.TECHNOTES,
    WY.ID,
    WY.NAME
    FROM REL_WINE_VINEYARD as r0 
    JOIN WINE as W ON r0.WINE_ID = W.ID
    JOIN VINEYARD AS WY ON r0.VINEYARD_ID = WY.ID